import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import { URL } from 'node:url';
const playersConfig=JSON.parse(await fs.readFile(new URL('./players.json',import.meta.url),'utf8'));let previous={};try{previous=JSON.parse(await fs.readFile(new URL('./data.json',import.meta.url),'utf8'))}catch{}
const SOURCES=[{id:'fitp',name:'FITP PUC',seeds:['https://www.fitp.it/Tornei/Ricerca-tornei'],maxPages:12},{id:'tennis-europe',name:'Tennis Europe',seeds:['https://www.tenniseurope.org/tournaments','https://te.tournamentsoftware.com/find'],maxPages:18},{id:'itf',name:'ITF pubblico',seeds:['https://www.itftennis.com/en/tournament-calendar/world-tennis-tour-juniors-calendar/'],maxPages:18},{id:'tennistalker',name:'TennisTalker pubblico',seeds:playersConfig.players.map(p=>p.tennisTalkerUrl).filter(Boolean),maxPages:4}];
const NAVIGATION_WORDS=/tournament|torneo|tabellon|draw|entry|acceptance|order.of.play|ordine.di.gioco|schedule|programma|calendar|calendario|player|giocatore/i;const SIGNALS={order_of_play:/order of play|ordine di gioco|programma incontri|schedule/i,registration:/iscritt[oaie]|entry list|acceptance list|accepted|main draw|qualifying|alternate/i,draw:/tabellone|draw|round of|quarti|semifinale|finale/i,match:/campo|court|vs\.?|contro|ore\s+\d{1,2}[:.]\d{2}/i};
const normalize=v=>(v||'').replace(/\s+/g,' ').trim();const absolute=(href,base)=>{try{return new URL(href,base).href.split('#')[0]}catch{return null}};const samePublicHost=(url,source)=>{try{const host=new URL(url).hostname.replace(/^www\./,'');if(source.id==='fitp')return host.endsWith('fitp.it');if(source.id==='tennis-europe')return host.endsWith('tenniseurope.org')||host.endsWith('tournamentsoftware.com');if(source.id==='itf')return host.endsWith('itftennis.com');return host.endsWith('tennistalker.it')}catch{return false}};
function classify(text){for(const[type,re]of Object.entries(SIGNALS))if(re.test(text))return type;return'mention'}function snippetAround(text,aliases){const upper=text.toUpperCase();let at=-1;for(const alias of aliases){at=upper.indexOf(alias.toUpperCase());if(at>=0)break}if(at<0)return'';return normalize(text.slice(Math.max(0,at-220),Math.min(text.length,at+420)))}function scoreLink(link){let score=0;const value=`${link.url} ${link.text}`;if(NAVIGATION_WORDS.test(value))score+=5;if(/2026|2027/.test(value))score+=2;if(/ital|ita|milano|roma|lecco|lombard/i.test(value))score+=3;if(/login|privacy|cookie|news|magazine|facebook|instagram|youtube/i.test(value))score-=8;return score}
const browser=await chromium.launch({headless:true});const context=await browser.newContext({locale:'it-IT',timezoneId:'Europe/Rome',userAgent:'CourtWatchPublicMonitor/1.0 (+public pages only)'});const findings=[];const tracked=new Set(previous.trackedUrls||[]);const sourceResults=[];
for(const source of SOURCES){const queue=[...new Set([...source.seeds,...(previous.trackedUrls||[]).filter(u=>samePublicHost(u,source))])].map(url=>({url,depth:0}));const visited=new Set();const diagnostics=[];while(queue.length&&visited.size<source.maxPages){const item=queue.shift();if(!item?.url||visited.has(item.url)||!samePublicHost(item.url,source))continue;visited.add(item.url);const page=await context.newPage();try{await page.goto(item.url,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(2000);for(const label of['Accetta','Accetta tutto','Accept','Accept all','Salva e chiudi']){const button=page.getByRole('button',{name:label,exact:false}).first();if(await button.count()){await button.click({timeout:700}).catch(()=>{});break}}await page.waitForTimeout(700);const title=normalize(await page.title());const text=await page.locator('body').innerText({timeout:8000}).catch(()=>'');const currentUrl=page.url();for(const player of playersConfig.players){const snippet=snippetAround(text,player.aliases||[player.name]);if(!snippet)continue;const type=classify(snippet);const key=`${player.id}|${currentUrl}|${type}`;if(!findings.some(f=>f.key===key)){findings.push({key,playerId:player.id,playerName:player.name,sourceId:source.id,sourceName:source.name,type,title:title||currentUrl,url:currentUrl,snippet,observedAt:new Date().toISOString()});tracked.add(currentUrl)}}if(item.depth<1){const links=await page.locator('a[href]').evaluateAll(nodes=>nodes.map(a=>({href:a.getAttribute('href'),text:(a.textContent||'').trim()})));const candidates=links.map(l=>({url:absolute(l.href,currentUrl),text:normalize(l.text)})).filter(l=>l.url&&samePublicHost(l.url,source)&&scoreLink(l)>0).sort((a,b)=>scoreLink(b)-scoreLink(a));for(const link of candidates.slice(0,source.maxPages))if(!visited.has(link.url))queue.push({url:link.url,depth:item.depth+1})}}catch(error){diagnostics.push({url:item.url,error:String(error.message||error).slice(0,180)})}finally{await page.close()}}sourceResults.push({id:source.id,name:source.name,status:visited.size?(diagnostics.length<visited.size?'ok':'partial'):'error',pagesChecked:visited.size,errorCount:diagnostics.length,diagnostics:diagnostics.slice(0,5)})}
await browser.close();const players=playersConfig.players.map(player=>({id:player.id,name:player.name,club:player.club||null,findingCount:findings.filter(f=>f.playerId===player.id).length}));const output={generatedAt:new Date().toISOString(),mode:'public-web',players,findings:findings.sort((a,b)=>a.playerName.localeCompare(b.playerName)||a.sourceName.localeCompare(b.sourceName)),trackedUrls:[...tracked].slice(0,200),sources:sourceResults};await fs.writeFile(new URL('./data.json',import.meta.url),JSON.stringify(output,null,2)+'\n');console.log(`CourtWatch: ${findings.length} riscontri pubblici, ${sourceResults.reduce((n,s)=>n+s.pagesChecked,0)} pagine controllate.`);
